github.com:
    users:
        antimidas:
            oauth_token: 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
    git_protocol: https
    user: antimidas
    oauth_token: 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
